### PR TITLE
Fix deprecation

### PR DESCRIPTION
**Pull request by arpangreat**

### CODE REVIEW

**Comment by arpangreat** [comment]
Sorry committed in wrong repo

**Comment by olimorris** [comment]
As a heads up, you can override colors instead of cloning this repo. It's documented in the readme

**Comment by arpangreat** [comment]
But is there any way I can change the lualine highlighting group , using `highlighters = {}` ?

**Comment by olimorris** [comment]
You can overwrite `fg_gutter` or `bg_statusline`. Or you could customise the theme as per l[ualine's docs](https://github.com/nvim-lualine/lualine.nvim/blob/d8c392dd75778d6258da4e7c55522e94ac389732/doc/lualine.txt#L165)

**Comment by arpangreat** [comment]
Thanks for the heads up ✌️ and so much Thanks for the colorsheme <3

**Pull request closed without merging**
