### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Mo8it**
I did fix the typo "focussed".

I did add an `or` in `config.lua` to not break user's existing config.

I did also fix comment typos with https://github.com/crate-ci/typos

### CODE REVIEW

**Comment by olimorris** [comment]
This is a great spot, thank you! Before I merge, I am going to add a deprecation warning as there maybe some people using it in its current wrongly spelled format.

**Comment by Mo8it** [comment]
No deprecation warning is needed since I did add edit this line:

https://github.com/Mo8it/onedarkpro.nvim/blob/a92297b47accfdf69e30664ca01a803ae37764ec/lua/onedarkpro/config.lua#L113

But if you want to keep the code clean, then I can remove this line with the `or` and you can add the deprecation warning.

**Comment by olimorris** [comment]
Great spot. Thanks very much!

I deleted my earlier comment as I saw the `or` you added. I'll add some deprecation warnings anyway as I plan to move people over to a new api over the coming months and want to give them a lot of warning.

**Comment by Mo8it** [comment]
Thank you for the great theme :heart:

**Pull request merged**
