### PR TITLE
Auto-compilation, faster load times

### PR DESCRIPTION
**Pull request by olimorris**
# Summary

This PR represents a big leap forward in the theme, thanks to the excellent work of [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim) and [catppuccin](https://github.com/catppuccin/nvim).

As the Neovim community continues to pursue faster startup times, the principle of caching becomes paramount. A previous issue with how the theme implemented caching was the need it placed on the user to remember to refresh the cache. It was hugely onerous.

The summary of the updates in this PR:

- The four themes which make up this colorscheme are now compiled to Lua bytecode and cached to disk
- The bytecode is then executed when the `vim.cmd([[colorscheme onedark]])` is executed
---
- The themes are auto-compiled when either the user's configuration or this plugin, changes
- This is done through some genius work by [Null Chilly](https://github.com/nullchilly) who had the original idea to hash a user's config to disk
- The colorscheme uses "fingerprinting" (a genius [EdenEast](https://github.com/EdenEast) idea) to determine if its codebase has changed and write that to disk
- Comparisons between the computed and disk values then determine if a new cache is required
---
- The principle of generating (or compiling) the themes is pretty much the same as when we were applying highlights in the previous version
- The difference now is that it gets converted to Lua bytecode instead of staying as raw Lua.
---
I've been testing this for about a week now. It's super fast. Each colorscheme loads in around `0.5ms`, down from `0.9ms` with the previous cache implementation and down from about `4ms` without caching.

Some minor improvements include:

- Can specify colors by the background color of the theme; not just by the name
- Each theme exists in its own `.vim` file making it easy to switch themes with external plugins
- More robust test cases and enhanced coverage

# Breaking Changes

I've scoured GitHub for how people load this plugin within their Neovim config and reflected that in some new test cases. As a result there should be no breaking changes for anyone.

The one issue people may encounter is if they use the `get_colors()` method to feed theme colors into their theme config. If they're using `onedark` then there will be no visual difference but if they're using any other theme, they'll need to explicitly call `get_colors("onelight")` for example.

# To do list

- [x] Add back autocmds and write subsequent tests
- [x] Add tests for fingerprints and caching
- [x] Test changes with existing users
- [x] Confirm that latency issues seen with previous caching are not seen in this version
- [ ] Improve error handling
- [ ] Add logging

### CODE REVIEW

**Comment by olimorris** [comment]
# To do list

- Test with existing users
- Confirm that latency issues seen with previous caching are not seen in this version
- Improve error handling
- Add logging

**Comment by mmirus** [comment]
@olimorris Sure thing! Anything I need to do besides loading this branch? (Enable caching in my config, etc.).

**Comment by mmirus** [comment]
First thing I'm seeing is that it seems I can no longer declare custom colors and use them in my config, or at least I'd need to do something different.

E.g., this type of thing now throws an error:

```lua
local onedarkpro = require("onedarkpro")
local color = require("onedarkpro.lib.color")
local colors = onedarkpro.get_colors(vim.g.onedarkpro_style)

onedarkpro.setup({
  dark_theme = "onedark_vivid",
  log_level = "debug",
  colors = {
    onedark_vivid = {
      medium_gray = color.lighten(colors.bg, 0.85, nil),
    },
  },
  highlights = {
    -- Illuminate
    IlluminatedWordText = { bg = "${medium_gray}" },
    IlluminatedWordRead = { bg = "${medium_gray}" },
    IlluminatedWordWrite = { bg = "${medium_gray}" },
  },
})

```

```
Error detected while processing /home/mmirus/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/mmirus/.config/nvim/lua/mmirus/onedark.lua:52: Vim(lua):E5108: Error executing lua :226: '${medium_gray}' is not a valid color
stack traceback:
        [C]: in function 'nvim_set_hl'
        :226: in function 'theme'
        ...ack/packer/start/onedarkpro.nvim/lua/onedarkpro/init.lua:121: in function 'load'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        /home/mmirus/.config/nvim/lua/mmirus/onedark.lua:52: in main chunk
        [C]: in function 'require'
        /home/mmirus/.config/nvim/lua/mmirus/init.lua:8: in main chunk
        [C]: in function 'require'
        /home/mmirus/.config/nvim/init.lua:1: in main chunk
stack traceback:
        [C]: in function 'cmd'
        /home/mmirus/.config/nvim/lua/mmirus/onedark.lua:52: in main chunk
        [C]: in function 'require'
        /home/mmirus/.config/nvim/lua/mmirus/init.lua:8: in main chunk
        [C]: in function 'require'
info:  Session restored from /home/mmirus/.local/share/nvim/sessions/\%home\%mmirus.vim
```

The line numbers in the error may be off, as the config example above isn't my actual config.

If you need, I can load up the minimal config and try to reproduce there.

**Comment by olimorris** [comment]
> @olimorris Sure thing! Anything I need to do besides loading this branch? (Enable caching in my config, etc.).

You should just need to make sure that `caching = true`. There's some other config options that I'll ask you to change if this works first time... 🤞🏼 .

**Comment by mmirus** [comment]
@olimorris I'm stuck at https://github.com/olimorris/onedarkpro.nvim/pull/134#issuecomment-1338165618 for the moment. LMK if you'd like me to try to repro that in a minimal config or try anything else!

**Comment by olimorris** [comment]
I should have remembered that you pull colors with the `get_colors` method and incorporate them into the your colors. If I allowed you to do something like:

```lua
colors = {
  onedark_vivid = {
    medium_gray = color.lighten("${bg}, 0.85, nil),
  },
}
```

would that be acceptable?

**Comment by mmirus** [comment]
I think that would actually be a more convenient API for that specific case, but I worry that not being able to access the actual color values programmatically might prove limiting (if that's the implication).

**Comment by olimorris** [comment]
The latest fix should allow you to do:

```lua
onedarkpro.setup({
    colors = {
        onedark_vivid = {
            medium_gray = color.lighten("${bg}", 0.85, nil),
        },
    },
    highlights = {
        IlluminatedWordText = { bg = "${medium_gray}" },
    },
})
```

Also, if you run `require("onedarkpro").get_colors()` you'll get the full color palette with `medium_gray` fully blended. The only downside is that you can only use the core color palette, not any generated ones.

**Comment by olimorris** [comment]
Actually...this isn't selecting `onedark_vivid` colors so will need to rework this.

**Comment by olimorris** [comment]
> Actually...this isn't selecting `onedark_vivid` colors so will need to rework this.

This should now be working. I note that you use `vim.g.onedarkpro_style`; as this was set after the theme was loaded then it makes more sense to ask users to explicitly state what theme they want to get colors from, like:

```lua
local colors = onedarkpro.get_colors("onedark_vivid")
```

If you don't do this then `get_colors` will use onedark's palette.

**Comment by olimorris** [comment]
@mrjones2014 - If you get some time this week, would you give this branch a test? My post at the top summarises all of the changes I've made. A big question I have is whether you experience any lagging. Conscious it was something you experienced with the previous caching iteration.

As an FYI, you shouldn't need to change _any_ of your config. I think you use the `get_colors` method so you may notice some of your colors look a little different if you're using a theme other than `onedark` and calling it before `setup`. If this is the case, something like `local colors = onedarkpro.get_colors("onedark_vivid")` will load the colors you expect.

**Comment by mrjones2014** [comment]
I use `get_colors` from my `feline.nvim` config but I have that lazy-load after `onedarkpro.nvim` loads (I load this before _anything_ else, otherwise you sometimes get a brief flashing of the Neovim default theme before this theme is applied). I think it should be fine in that case then, since `feline.nvim` is loading after?

I can give this branch a test. Should I remove the autocmd that calls `:OnedarkproCache` on `PackerComplete`?

**Comment by mrjones2014** [comment]
I had to change `window_unfocused_color` to `highlight_inactive_windows` and I also had to explicitly set the `NormalNC` highlight for it to work, it was defaulting to the same bg color as `Normal`.

**Comment by olimorris** [comment]
> I had to change `window_unfocused_color` to `highlight_inactive_windows` and I also had to explicitly set the `NormalNC` highlight for it to work, it was defaulting to the same bg color as `Normal`.

Ooooof good spot!

**Comment by olimorris** [comment]
Okay this should now be fixed so you can revert your config to the original.

Are you seeing swift load times?

**Comment by mrjones2014** [comment]
Holy shit, yeah, 0.009666ms ⚡🚀

**Comment by mrjones2014** [comment]
That's like a nearly 50x startup time improvement for me

**Comment by olimorris** [comment]
@mmirus - Your excellent autocmds are now incorporated into the cache as well

**Comment by mmirus** [comment]
@olimorris Okay, no errors now on the latest commit here with no changes required to my config. :ok_hand: I did subsequently specify the variant in the `get_colors` call, though, per your note.

So far, the only difference I have noticed is that the lualine styles are pretty different. Is that intentional?

For example:

image

vs

image

**Comment by olimorris** [comment]
> So far, the only difference I have noticed is that the lualine styles are pretty different. Is that intentional?

@mmirus - Ooooh that is not intended! I've made some changes to the lualine config...could you see if that works?

**Comment by mmirus** [comment]
@olimorris Sorry to be late on this, but seems like we have some styling differences before and after this PR. Specifically, I'm noticing extra bolding related to functions and methods.

I suspect this is actually intentional, and the new version is what was always supposed to be happening? I do have `styles = { functions = "bold" }` in my config, and the new bolds obey if I disable that. To be clear, I don't mind the new bolds (in fact, this makes TSX render more like JS and TS), just making sure all is as intended.

**Before**

lua
image

tsx
image

**After**

lua
image

tsx
image

**Comment by olimorris** [comment]
That is indeed intended. I've "improved" some of the treesitter groups such as `@keyword.function` in this case. I felt it made sense to link it to the function style and `@keyword.operator` to the operators style.

One of those grey areas where they could arguably be all wrapped up into just the keyword style. What swung it for me is that Treesitter becomes more detailed every few months and it felt like I should differentiate keywords

**Comment by mmirus** [comment]
Sounds good to me! Thanks for your work in this PR.

**Pull request merged**
