### PR TITLE
fix telescope titles color

### PR DESCRIPTION
**Pull request by maxmx03**
## before

https://user-images.githubusercontent.com/50273941/180245940-ae618794-4127-47c7-a2ff-e7ffd42cce27.mp4

https://user-images.githubusercontent.com/50273941/180245967-188a8bb7-dfa6-40a3-9871-ad8f1d9fa6b1.mp4

## after

https://user-images.githubusercontent.com/50273941/180246010-7c0a730c-c959-4a61-8ca6-7192283ed1e2.mp4

https://user-images.githubusercontent.com/50273941/180246022-44594422-e442-4342-ab10-60ad09ec6558.mp4

### CODE REVIEW

**Comment by olimorris** [comment]
This is great thanks so much for fixing.

**Comment by olimorris** [comment]
@maxmx03 - Apologies I merged this when I should have considered the wider implications of this.

I take your point around the layout of your Telescope setup and not having the `results` title coloured, may look a bit odd. However for my layout, it's visually obstructing to have it highlighted:

Screen Shot 2022-07-22 at 16 10 34@2x

To achieve your desired outcome you can use the following config:

```lua
require("onedarkpro").setup({
  hlgroups = {
    TelescopePreviewTitle = { fg = "${bg}", bg = "${green}" },
    TelescopeResultsTitle = { fg = "${bg}", bg = "${purple}" },
    TelescopePromptTitle = { fg = "${bg}", bg = "${purple}" },
  }
})
```

I'll mull on what to do for this moving forward as this is the first time someone has raised this issue.

**Comment by mmirus** [comment]
I think I hit this after the theme's Telescope styles were updated a little while back. I spent some time working around it and came up with this to get back to something closer to the previous telescope styles:

```
local onedarkpro = require('onedarkpro')
local utils = require("onedarkpro.utils")
local colors = onedarkpro.get_colors(vim.g.onedarkpro_style)
local telescope_prompt = utils.darken(colors.bg, 0.85)
onedarkpro.setup({
  -- ...
  hlgroups = {
    TelescopeBorder = { fg = "${gray}" },
    TelescopeResultsTitle = { bg = "${blue}" },
    TelescopePromptBorder = { fg = "${gray}", bg = telescope_prompt },
    TelescopePromptPrefix = { bg = telescope_prompt },
    TelescopePromptNormal = { bg = telescope_prompt },
  },
})

```

image

But then decided to try rolling with the changes to the theme to see if I would adjust, and it hasn't bothered me. :sweat_smile:

**Comment by olimorris** [comment]
The merging of the telescope styles was something I won't do again...rather risqué and opinionated. My justification at the time was "I think it looks really nice and I'll see what the general feedback is". One person raised the issue of the borders, completely get that, and it was a couple of highlights to fix I believe but do need to think more about this. Opinions welcome!

**Comment by mmirus** [comment]
It does look clean and modern with the updated theme styles, but you do lose some of the more explicit separation and labeling. Just a matter of preference, probably. The change did feel a little unexpected and almost like it went beyond simple color theming into Telescope layout/config territory (even though in fact all the changes were to colors, if I recall).

Beyond a point, you probably don't want to balloon the codebase/config with too many options you have to document and support ("enable_opinionated_telescope_styles"), so maybe this type of thing would be a good candidate for inclusion in a recipes section instead of shipping it in the plugin itself.

**Comment by olimorris** [comment]
Appreciate all of the feedback and have reverted it back to the original Telescope theme. Agree on the `recipes` idea. Really great suggestion.

**Comment by mmirus** [comment]
Thanks! Pleasure collaborating with you as always! And TY @maxmx03.

**Pull request merged**
