### PR TITLE
Add dashboard hi groups support.

### PR DESCRIPTION
**Pull request by yuukibarns**

### CODE REVIEW

**Comment by olimorris** [comment]
Could you a screenshot of how Dashboard looks?

**Comment by yuukibarns** [comment]
dashboard_preview

**Comment by olimorris** [comment]
Oh that looks awesome!

I'd ask that we make the main header purple. Just because it's the primary/standout color for this theme. Otherwise this is great and I'll be happy to merge.

**Review by yuukibarns — COMMENTED** [review]
It comes form [tokyonight](folke/tokyonight.nvim). I've just moved from tokyonight to this theme, so it is a small copy-and-paste.

**Comment by olimorris** [comment]
That's why it looks more like Tokyonight then this theme 😉

**Comment by yuukibarns** [comment]
In fact i always hesitate to decide which color to pick...
I think you may have a much more profound knowledge than me in this theme, and it is up to you to tweak your own plugin, so you don't need my audit, change this PR as you like.😃

**Pull request closed without merging**
