### PR TITLE
refactor: full rewrite of plugin

### PR DESCRIPTION
**Pull request by olimorris**
## Context
I feel like there can be something arrogant about authors rewriting their Neovim plugins when nearly zero features are added. Especially when it's a color scheme 😆 . The risk of breaking users configs should *really* outweigh the gain. At least it would in an enterprise environment.

However, in recent months, I've thought long and hard about what features I'd like to add into the plugin. Contemplating how they'd be included into the plugin made me realise that the already bloated `utils.lua` file (c. 400 loc!) would be the likely destination. Also, debugging user's issues has become increasingly harder as I struggle to recall how certain features were implemented.

Two hard facts which have led me to this point...

## Principles
So in writing this refactor, I set myself two core principles:

1. Do not rewrite the `README.md` file; *and*
2. Do not make any changes that will result in the user having to change their existing config.

Simple and obvious, right? From the users perspective, nothing should noticeably change and basically, don't f*ck with the existing API.

## So what has changed
[Nightfox.nvim](https://github.com/EdenEast/nightfox.nvim) has served as an inspiration for a very long time (I may need to change the README to thank Eden East!) and a lot of the beautiful modularity and separation has come from that. Particularly for how a users custom config is handled and how colors and highlights are implemented. I sought to simplify the structure of the plugin even more whilst allowing a base to add some nice new features further down the line. I benchmarked how highlights are created in Neovim and chose the most performant option. And I split the necessary utils into logical files.

In detail:
- The API and config remains the same
- Themes have been rewritten to be consistent and far more logical - this *may* allow future themes to be added further down the line
- Logical separation of components, `lib`, `highlights`, `themes`, `utils` etc.
- User overrides are stored in separate tables to allow consumption in other parts of the plugin
- For Neovim 0.7+ users, the new `vim.api.nvim_set_hl` can be used
- Many more [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) tests have been added to allow for greater test coverage

Edit: I **have** refactored `README.md` to simplify it but no changes to the actual API or how a user can load the color scheme

### CODE REVIEW

**Comment by olimorris** [comment]
Before I consider merging this into `main`, would you be wiling to test this out @mmirus, @maxmx03, @LC0117?

You just need to point at the `develop` branch and essentially, everything should work. Except for filetype highlights, I am reworking those today and tomorrow.

**Comment by mmirus** [comment]
Hey, @olimorris! Exciting stuff! Happy to help do some testing. I hit a problem on the new version with my existing config, so I grabbed the minimal config and was able to reproduce.

The error:

```
Error detected while processing /home/mmirus/minimal.lua:
E5113: Error while calling lua chunk: /home/mmirus/minimal.lua:50: Vim(lua):E5108: Error executing lua ...ck/packer/start/onedarkpro.nvim/lua/onedarkpro/theme.lua:29: attempt to index field
 'config' (a nil value)
stack traceback:
        ...ck/packer/start/onedarkpro.nvim/lua/onedarkpro/theme.lua:29: in function 'load'
        ...ack/packer/start/onedarkpro.nvim/lua/onedarkpro/init.lua:54: in function 'load'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        /home/mmirus/minimal.lua:50: in main chunk
stack traceback:
        [C]: in function 'cmd'
        /home/mmirus/minimal.lua:50: in main chunk
```

The config:

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/onedarkpro"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
    install_plugins = true
end

local packer = require("packer")

packer.init({
    package_root = test_dir .. "/pack",
    compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
    -- Packer can manage itself
    use("wbthomason/packer.nvim")

    use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
    use({ "olimorris/onedarkpro.nvim", branch = "develop" })

    if install_plugins then
        packer.sync()
    end
end)

local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
    treesitter.setup({
        ensure_installed = "all",
        ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
        highlight = { enable = true },
    })
end

local ok, onedarkpro = pcall(require, "onedarkpro")
if ok then
    vim.cmd("colorscheme onedarkpro")
end

```

Note that the same minimal config on the latest release of the theme does work.

**Comment by olimorris** [comment]
Thanks @mmirus! I was able to recreate this in a plenary test as well so have hopefully fixed in the latest push.

**Comment by LC0117** [comment]
It seems that the utils module has been changed so the `utils.darken` api cannot be called this way. Howerver, there is a 'lib.color.darken' api.

**Comment by mmirus** [comment]
Right you are! My config loads without error after replacing instances of `darken` and `lighten` like this:

```lua
local utils = require("onedarkpro.utils")
local colors = onedarkpro.get_colors(vim.g.onedarkpro_style)
local dark_gray = utils.darken(colors.bg, 0.85)
```

with instances like this:

```lua
local color = require("onedarkpro.lib.color")
local colors = onedarkpro.get_colors(vim.g.onedarkpro_style)
local dark_gray = color.darken(colors.bg, 0.85)
```

Obviously, if that usage of utils was intended to be a public API that went unchanged, this is broken and doesn't meet the goals of the refactor, but I'm guessing that was never the intent for this module. (@olimorris)

I'll continue using the new version and report back if I spot anything else!

**Comment by olimorris** [comment]
> Possibly reaching into utils in this way isn't a supported public API that was supposed to continue to function with the refactor?

Okay great spot. I shall make sure I add all of this back to the utils file. In time I may deprecate parts of the public API but overall goal with the rewrite is not to break anything.

Should have built in telemetry into the colorscheme to find out how people use it 🤣.

**Comment by olimorris** [comment]
@mmirus have added back the APIs. Please let me know if that works 👍🏼

**Comment by mmirus** [comment]
@olimorris I updated to the latest commit and reverted back to utils, and it worked now. That said, I'll keep using the helper from lib if utils will just be a compatibility layer that may be deprecated.

**Comment by olimorris** [comment]
Awesome thank you for testing!

**Comment by mmirus** [comment]
It seems that something with the highlights from [https://github.com/folke/todo-comments.nvim](todo-comments.nvim) doesn't work right on the new version.

Before:

image

After:

image

LMK if there's any more info I can provide or testing I can do.

**Comment by olimorris** [comment]
Are you a detective in your spare time?! What a spot. And really bizarre. That red is not in the scheme at all. I shall put my detective hat on.

**Comment by olimorris** [comment]
@mmirus should be solved now. I was overwriting some of the native LSP highlight groups with LSP Saga. The new `vim.api.nvim_set_hl` command takes no prisoners. Seemingly with the old way of writing highlights, you could somehow get away with overlapping highlights. Maybe to do with how the plugins were loaded in a certain order and now the rewrite has changed that.

Either way. Thanks for spotting. What a find!

**Comment by mmirus** [comment]
Nice! I have confirmed this is fixed on the latest commit. TY!

> Maybe to do with how the plugins were loaded in a certain order

That sounds like a rough world to live in, if that's the correct diagnosis. Hopefully the new method affords greater consistency.

**Comment by olimorris** [comment]
Filetype highlights have now been added back.

Some great new functionality that was added in 0.7 which allows you to create namespaces for highlights. So it's really easy to create a custom namespace for each filetype and create their own individual highlights. Then you can use `vim.api.nvim__set_hl_ns()` to apply the namespace when you move to that filetype or simply apply the default `0` namespace.

I've written tests but @mmirus would appreciate your feedback at some point.

**Comment by mmirus** [comment]
I did a quick test and filetype highlights don't seem to be working.

My existing config did not apply them, and neither did this minimal config:

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/onedarkpro"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
    vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
    vim.cmd("packadd packer.nvim")
    install_plugins = true
end

local packer = require("packer")

packer.init({
    package_root = test_dir .. "/pack",
    compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
    -- Packer can manage itself
    use("wbthomason/packer.nvim")

    use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
    -- use("olimorris/onedarkpro.nvim")
    use({ "olimorris/onedarkpro.nvim", branch = "develop" })

    if install_plugins then
        packer.sync()
    end
end)

local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
    treesitter.setup({
        ensure_installed = "all",
        ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
        highlight = { enable = true },
    })
end

local ok, onedarkpro = pcall(require, "onedarkpro")
if ok then
    onedarkpro.setup({
	filetype_hlgroups = {
    	    yaml = {
		TSField = { fg = "${red}" },
	    },
	},
    })
    vim.cmd("colorscheme onedarkpro")
end

-- Other...
vim.api.nvim_set_option('expandtab', true)
vim.api.nvim_set_option('shiftwidth', 4)
vim.api.nvim_set_option('softtabstop', 4)

```

You would expect the field names to be red, but they are not:

image

**Comment by olimorris** [comment]
@mmirus and to check you're on Neovim 0.7 or above?

**Comment by olimorris** [comment]
I think I've fixed it...super weird error.

Once again, thanks for spotting and fixing. I owe you some beers!

**Comment by mmirus** [comment]
Yep, working now! :grin: :beers:

**Comment by olimorris** [comment]
We're now feature complete with the previous branch and I will look to merge next week.

Thanks everyone for your feedback.

**Comment by mrjones2014** [comment]
I checked out this branch and everything works as intended with no changes to my config. My startup time is noticeably improved, though 👏 🎉

**Comment by olimorris** [comment]
> I checked out this branch and everything works as intended with no changes to my config. My startup time is noticeably improved, though 👏 🎉

Now that's the type of feedback I'll have a Friday 🍺 to! Thanks @mrjones2014. The Neovim 0.7 highlight APIs are the USP tbh.

**Comment by petobens** [comment]
Hi! There's one thing I cannot quite get to work with this branch. If I define my color palette like so: https://github.com/petobens/dotfiles/blob/9be10fb19db6859163b89470b452267968bc2745/nvim/lua/plugin-config/onedark_config.lua#L3 
And then have a lualine theme that uses such palette as in https://github.com/petobens/dotfiles/blob/nvim-lua/nvim/lua/lualine/themes/onedarkish.lua 
For some reason the lualine file doesn't read my new palette colors but rather prints the following when calling `require('onedarkpro').get_colors()`:
```
{
  bg = "#282c34",
  bg_statusline = "#33373E",
  black = "#282c34",
  blue = "#61afef",
  color_column = "#2E323A",
  cursorline = "#2E323A",
  cyan = "#56b6c2",
  diff_add = "#003e4a",
  diff_delete = "#501b20",
  diff_text = "#005869",
  fg = "#abb2bf",
  fg_gutter = "#696B71",
  gray = "#5c6370",
  green = "#98c379",
  highlight = "#e2be7d",
  indentline = "#373B42",
  light = false,
  name = "onedark",
  none = "NONE",
  orange = "#d19a66",
  purple = "#c678dd",
  red = "#e06c75",
  selection = "#53565D",
  virtual_text_error = "#E9989E",
  virtual_text_hint = "#78C5CE",
  virtual_text_information = "#90C7F4",
  virtual_text_warning = "#EDD3A3",
  white = "#abb2bf",
  yellow = "#e5c07b"
}
```

Is this an import/require order thing? I cannot quite cook a minimal.lua file to reproduce it.

**Comment by olimorris** [comment]
@petobens even if you pass `vim.g.onedarkpro_theme` to the `get_colors` function?

Given the amount of overrides to colors and highlight groups, you may prefer creating your own color scheme.

**Comment by petobens** [comment]
>  Have you put an after option in your Packer config so Lualine loads after onedarkpro?

You mean something like
```lua
    use({
        'olimorris/onedarkpro.nvim',
        branch = 'develop',
        config = function()
            require('plugin-config/onedark_config')
        end,
        after = 'lualine',
    })
    use({
        'nvim-lualine/lualine.nvim',
        requires = {
            'kyazdani42/nvim-web-devicons',
            'arkav/lualine-lsp-progress',
            'olimorris/onedarkpro.nvim',
        },
        config = function()
            require('plugin-config/lualine_config')
        end,
    })
```
That gives an error in my case stating that lualine and onedarkpro are not related. 

> Given the amount of overrides to colors and highlight groups, you may prefer creating your own color scheme.

The things is that adding `require('onedarkpro').get_colors()` in my lualine theme works in master but not in this refactor branch.
I can workaround this by simply copying my whole palette in the lualine theme file but I'd rather call `get_colors()`.

**Comment by olimorris** [comment]
@petobens I think this is fixed in my latest commit. This actually puts `get_colors` pretty much back to what it is on `main`.

**Comment by petobens** [comment]
Indeed. Thank you :)

**Comment by olimorris** [comment]
Thanks again for testing everyone!

**Comment by mmirus** [comment]
Congrats on the rewrite!

**Pull request merged**
