### PR TITLE
Match comment color more closely to vscode theme

### PR DESCRIPTION
**Pull request by mmirus**
This may be more controversial, but it does more closely match the upstream vscode theme.

Pros:
- closer upstream match
- better contrast with background for reading comments

Con:
- less differentiation between comment color and `fg`

I got the color for the dark themes from the vscode repo; the light theme color I just eyeballed.

nvim on left, vscode on right:

image

### CODE REVIEW

**Comment by olimorris** [comment]
Not controversial at all. I was making some images for the readme earlier today, noticed the discrepancy and thought I'd leave it until someone pointed it out; in case it didn't bother anyone. Thanks for the effort with this PR!

**Comment by mmirus** [comment]
"Bother" might be too strong a word for my feeling about this, but it probably does make things a bit more readable. :grin: 

Funnily enough, on the flip side the line numbers are brighter in neovim and darker in vscode, which makes them _harder_ to read in vscode (but possibly "slicker" looking).

You can test it out with this line, if you want:

```lua
    LineNr = { bg = "${bg}", fg = "#495162" },
```

**Comment by olimorris** [comment]
Yeah so I much prefer the "harder to read" style colors 😆 . I'd be happy to accept your `LineNr` as a PR too

**Comment by mmirus** [comment]
😂 I was a little conflicted about the comment color for the same reason, TBH. It's nice having an objective baseline in the form of the vscode theme rather than having to make a lot of decisions about what looks better and worse with no anchor. Then we can always override locally for personal preference. 

That said, I'm a hypocrite because if I PR the line number change, I'm not going to replace the purple color for the active line with the light gray that vscode has. I like the purple!

**Comment by mmirus** [comment]
If I did PR the line number, should I keep adding variables for these to the palette? Or should I just put the color code right in `editor.lua`?

**Comment by olimorris** [comment]
Actually, let's add `line_number` to the generated palette. Not strictly true but it's also not strictly a core palette color. Maybe below your `diff_add`, `diff_delete` and `diff_text`?

**Pull request merged**
