### PR TITLE
Add user commands to export the loaded theme to Windows Terminal or Alacritty

### PR DESCRIPTION
**Pull request by MrStrik3**
Add the OnedarkExportTo user commands

### CODE REVIEW

**Comment by olimorris** [comment]
👋🏼 and thanks for the PR. It could be a really useful addition!

Some initial thoughts:

- Can we add a Kitty theme?
- I think the Alacritty theme is missing `bright` colors as per the [current included one](https://github.com/olimorris/onedarkpro.nvim/blob/main/extras/alacritty_onedark.yml)
- Regarding the bright colors, I see in the windows theme you're using `"brightRed": "{red}"`, it would be great if we can incorporate something like `require('onedarkpro.helpers').lighten('red', 10, 'onedark')` to differentiate. This might be tricky so happy to work with you on this
- It would be great to add some test coverage to verify that the exports are working as expected

**Comment by MrStrik3** [comment]
I wanted to make sure you were open to approve PRs from strangers before putting too much work into it :) If you are open to it, I would be happy to improve it. Lua is new to me, I will fix this thing in the pipeline with "stylua", sorry for that

- Point #1 : I started to write the "colortemplate" for kitty but I didn't have a way to test it since my laptop has Windows and WSL. I never tried Kitty on WSL, It might work. I would have to give it a try. I can create it and you can test it on your own
- Point #2, #3 : I didn't create the bright colors because I am very very very bad at picking colors, this is why I use your theme :D I saw the lighten and darken functions in the codebase, these are a very good idea. If you can provide a number to use as a parameter in the lighten function, I will be happy to make the changes in the color templates in this PR
- No problem I can look into the test coverage. I am new to Lua and Neovim, I will start to look into it :)

**Comment by olimorris** [comment]
Yep I am definitely happy for PRs especially when they add great functionality. Your feature has been something I've ignored for a while so very appreciative of your work.

Let me know when you're happy and I'll try it out and review the code more thoroughly. First glance looks great.

**Comment by MrStrik3** [comment]
Great! You can test it out whenever you want. All OnedarkproExportto* user commands are working in the branch/PR. Only the test coverage is missing.  

Giving a little bit more thought into it, I had another idea. A 'OnedarkproExportTo'  user command that would open a floating window. This window would display the theme color palette and the generated terminal configs. Something similar to what lazy.nvim does. Toggle buttons at the top with the terminal configs displayed under. I will work on a prototype and ask for your comments after

image

**Comment by olimorris** [comment]
> Great! You can test it out whenever you want. All OnedarkproExportto* user commands are working in the branch/PR. Only the test coverage is missing.

Awesome, I'll give it a try tonight.

> Giving a little bit more thought into it, I had another idea. A 'OnedarkproExportTo' user command that would open a floating window. This window would display the theme color palette and the generated terminal configs. Something similar to what lazy.nvim does. Toggle buttons at the top with the terminal configs displayed under. I will work on a prototype and ask for your comments after

Also, this is a great idea and completely up for that too. May need to think where we place the utilities for a popup but in principle I think it would be a great addition to the theme.

**Comment by MrStrik3** [comment]
I finally came up with a prototype. Do you have any comments or suggestions before I dig deeper into the code ? The colors used in the "menu bar" don't really matter, you can change them after the PR had been merged or add the menubar's colors into the onedarkpro.setup({}) later :P
image

**Comment by olimorris** [comment]
Wow this looks great 👍🏼️. Playing around yesterday I may move the templates into a separate folder...need to think about the structure but otherwise it's great.

Could we break the menu into a separate PR too?

**Comment by MrStrik3** [comment]
Of course, a new PR will not be a problem. I will also add the test coverage to the next PR too. I never did it, it's all new to me. What tool do you use for lua test coverage ?

**Comment by olimorris** [comment]
@MrStrik3 I've made some low value amendments (snake casing) and changed the folder structure somewhat. I'm going to update the readme then I think we can merge! Super awesome PR and thanks so much.

**Pull request merged**
