### PR TITLE
add @variable highlight for lua

### PR DESCRIPTION
**Pull request by mrjones2014**
I personally think the `@variable` selector needs a highlight, feel free to close if you disagree and I'll put it in my personal config.

### CODE REVIEW

**Comment by mrjones2014** [comment]
I can't reproduce the test failure locally 🤔

**Comment by olimorris** [comment]
> I personally think the `@variable` selector needs a highlight, feel free to close if you disagree and I'll put it in my personal config.

It should be red by default. The default Treesitter one is:

`["@variable"] = { fg = theme.palette.red, style = config.styles.variables }`

**Comment by olimorris** [comment]
For the `@operator` highlight group, with the current settings:

Screen Shot 2022-10-17 at 16 45 37@2x

With your suggestion:

Screen Shot 2022-10-17 at 16 46 20@2x

With VS Code:

Screen Shot 2022-10-17 at 16 46 58@2x

**Comment by mrjones2014** [comment]
Oh, hmm, for some reason `@variable` is using the `Normal` colors for me :thinking:

**Comment by olimorris** [comment]
Phew! Good spot.

**Pull request closed without merging**
